name: habit-tracker

services:
  habit-tracker-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - SPRING_PROFILES_ACTIVE=prod
    container_name: habit-tracker-backend
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - APP_FRONTEND_URL=${FRONTEND_URL}               # URL del frontend
      - APP_DOMAIN_URL=${DOMAIN_URL}                   # Dominio completo
      - OAUTH2_REDIRECT_URI=${OAUTH2_REDIRECT_URI}     # Redirect URI per Google
      - SERVER_SERVLET_SESSION_COOKIE_SECURE=true
      - SERVER_SERVLET_SESSION_COOKIE_SAME_SITE=none
      - SPRING_SECURITY_REMEMBER_ME_KEY=${REMEMBER_ME_KEY}
      - SERVER_SERVLET_SESSION_TIMEOUT=${SESSION_TIMEOUT}
    env_file:
      - .env
    networks:
      - habit-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  habit-tracker-frontend:
    image: nginx:alpine
    container_name: habit-tracker-frontend
    ports:
      - "8083:80"  # Espone il frontend sulla porta 8083
    volumes:
      - ./frontend:/usr/share/nginx/html  # Monta i file HTML, CSS e JS
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Monta la configurazione Nginx
    networks:
      - habit-network
    restart: unless-stopped

networks:
  habit-network:
    driver: bridge
